### ISSUE TITLE
OSError: [Errno 22] Invalid argument: '1200_forests/library.txt'

### ISSUE THREAD

**Issue by mmaechtel** [hotbso/o4xpsm#3]
How to solve this error?

PS D:\X-Plane 12\Custom Scenery\o4xp_Seasons_Manager> python .\o4xpsm_install.py
INFO:o4xpsm_install:Version: 1.10
INFO:o4xpsm_install:args: ['.\\o4xpsm_install.py']
INFO:o4xpsm_install:
INFO:o4xpsm_install:Parsing scenery_packs.ini
INFO:o4xpsm_install:Global_Forests_v2 detected
INFO:o4xpsm_install:simHeaven_X-World_Vegetation_Library detected
INFO:o4xpsm_install:
INFO:o4xpsm_install:Checking links
INFO:o4xpsm_install:path: ..\..\Resources/default scenery/1200 forests
INFO:o4xpsm_install:creating junction 1200_forests -> ..\..\Resources/default scenery/1200 forests
Junction created for 1200_forests <<===>> D:\X-Plane 12\Resources\default scenery\1200 forests
INFO:o4xpsm_install:path: ..\..\Custom Scenery/simHeaven_X-World_Vegetation_Library/
INFO:o4xpsm_install:creating junction simHeaven_X-World_Vegetation_Library -> ..\..\Custom Scenery/simHeaven_X-World_Vegetation_Library/
Junction created for simHeaven_X-World_Vegetation_Library <<===>> D:\X-Plane 12\Custom Scenery\simHeaven_X-World_Vegetation_Library
INFO:o4xpsm_install:path: ..\..\Custom Scenery/Global_Forests_v2/
INFO:o4xpsm_install:creating junction Global_Forests_v2 -> ..\..\Custom Scenery/Global_Forests_v2/
Junction created for Global_Forests_v2 <<===>> D:\X-Plane 12\Custom Scenery\Global_Forests_v2
INFO:o4xpsm_install:
INFO:o4xpsm_install:Creating library.txt
INFO:o4xpsm_install:Processing XP12 native forests
Traceback (most recent call last):
  File "D:\X-Plane 12\Custom Scenery\o4xp_Seasons_Manager\o4xpsm_install.py", line 237, in <module>
    season = parse_lib("1200_forests/library.txt")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\X-Plane 12\Custom Scenery\o4xp_Seasons_Manager\o4xpsm_install.py", line 45, in parse_lib
    with open(name, "r") as f:
         ^^^^^^^^^^^^^^^
OSError: [Errno 22] Invalid argument: '1200_forests/library.txt'
PS D:\X-Plane 12\Custom Scenery\o4xp_Seasons_Manager>

**Comment by mmaechtel** [comment]
ah! Now I tried to execute the python script in my vscode terminal, there it worked .... hmmm
